name: Atualizador Automatico Nil All UFC

on:
  schedule:
    # O cron usa o padrão: Minuto Hora Dia Mes Dia_da_Semana
    # '0 13 * * 3' significa: Toda Quarta-feira às 13:00 UTC (10:00 Horário de Brasília)
    - cron: '0 13 * * 3' 
  workflow_dispatch: # Isso cria um botão para você rodar o robô na hora que quiser

jobs:
  build:
    runs-on: ubuntu-latest # O GitHub abre um computador Linux virtual para rodar seu script
    steps:
      - name: Baixando os arquivos do seu repo
        uses: actions/checkout@v3

      - name: Instalando o Python no Linux
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalando bibliotecas necessárias
        run: pip install requests beautifulsoup4

      - name: Executando o Robô Scraper
        run: python scraper.py

      - name: Salvando os novos dados no GitHub (Commit)
        run: |
          git config --global user.name "Nil All Bot"
          git config --global user.email "bot@nilall.com"
          git add lutas.json
          git commit -m "UFC Data: Atualização Automática" || exit 0
          git push
